name: CRD Windows

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set timezone
      run: tzutil /s "India Standard Time"

    - name: Install CRD
      run: |
        Invoke-WebRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile crd.msi
        Start-Process msiexec.exe -ArgumentList '/i crd.msi /quiet /norestart' -Wait

    - name: Set password
      run: net user runneradmin admin@123

    - name: Fix display
      run: |
        Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "LogPixels" -Value 96
        Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "Win8DpiScaling" -Value 1

    - name: Start CRD
      run: |
        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" `
          --code="${Env:CRD_CODE}" `
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" `
          --name="gh-runner-$Env:RUNNER_TRACKING_ID" `
          --pin=123456
      env:
        CRD_CODE: ${{ secrets.CRD_CODE }}

    - name: Keep Alive
      run: Start-Sleep -Seconds 21600
